import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="min-h-[calc(100vh-68px)] ">
        <Header />
        {children}
      </body>
      <Footer />
    </html>
  );
}
